import type { Metadata } from "next";
import { DM_Serif_Display, DM_Sans } from 'next/font/google'
import "./globals.css";


const dmSerif = DM_Serif_Display({
  weight: ['400'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-heading',
})

const dmSans = DM_Sans({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  variable: '--font-body',
})
export const metadata: Metadata = {
  title: "Full Stack Developer | Carlos Velasco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSerif.variable} ${dmSans.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-main text-text">{children}</body>
    </html>
  );
}
