/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Manuel W. (https://sketchfab.com/nebulariser)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/luke-skywalker-lightsaber-f33fb37937a34aca8aa8602820460e51
Title: Luke Skywalker Lightsaber
*/

import { useGLTF } from '@react-three/drei';

const LightSaber = (props) => {
  const { nodes, materials } = useGLTF('/models/luke_skywalker_lightsaber.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 2.129, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Steel_II}
        />
      </group>
      <group position={[0, 6.151, 0]} scale={[1.364, 0.529, 1.364]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.Steel_II}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[1.942, -3.88, 0]} scale={[1.564, 1.161, 0.865]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials.Brass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Black}
        position={[0, 2.495, 0]}
        scale={0.529}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Black}
        position={[0, 2.961, 0]}
        scale={[0.652, 0.529, 0.652]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Steel_II}
        position={[0, 3.085, 0]}
        scale={[0.993, 0.529, 0.993]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.Brass}
        position={[0, 3.416, 0]}
        scale={[0.85, 0.529, 0.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Brass}
        position={[0, 4.182, 0]}
        scale={[0.461, 0.529, 0.461]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Steel_II}
        position={[0, 4.819, 0]}
        scale={[0.666, 0.529, 0.666]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Steel_II}
        position={[0, 5.322, 0]}
        scale={[0.957, 0.529, 0.957]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.Steel_II}
        position={[0, 5.889, 0]}
        scale={[1.144, 0.529, 1.144]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.Steel_II}
        position={[0, -5.121, 0]}
        scale={[1.05, 0.529, 1.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.Steel_II}
        position={[0, -5.412, 0]}
        scale={[1.019, 0.529, 1.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.Steel_II}
        position={[0, -8.663, 0]}
        scale={[0.967, 0.529, 0.967]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Steel_II}
        position={[0, -8.44, 0]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[1.025, 0.547, 1.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.Steel_II}
        position={[0, -9.338, 0]}
        scale={[1.059, 0.529, 1.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.Steel_II}
        position={[0, 6.282, 0]}
        scale={0.549}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.Steel_II}
        position={[1.382, -3.88, 0]}
        scale={[1, 1.148, 0.556]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.Brass}
        position={[1.015, -3.84, 0]}
        scale={[1, 1.161, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.Green}
        position={[1.415, -2.884, -0.582]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.151}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.material}
        position={[1.415, -3.429, -0.582]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={0.151}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.Steel_II}
        position={[1.153, -3.156, -0.57]}
        rotation={[Math.PI / 2, -Math.PI / 4, 0]}
        scale={[0.076, 0.044, 0.076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.Black}
        position={[1.53, -4.567, -0.544]}
        scale={[0.209, 0.209, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.Steel_II}
        position={[0, 6.609, 0]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials.material_0}
        position={[1.946, -3.88, 0]}
        scale={[1, 1.161, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_57.geometry}
        material={materials.Steel_II}
        position={[1.282, -7.892, 0]}
        rotation={[0, 0, 1.297]}
        scale={[1, 0.5, 1]}
      />
    </group>
  );
};

useGLTF.preload('/models/luke_skywalker_lightsaber.glb');

export default LightSaber;
